version: '3'

services:
  website:
    build: ./website
    container_name: almundo-website
    command: npm run start:docker
    ports:
      - '4200:4200'
    volumes:
      - './website/:/usr/src/website'
      - /usr/src/website/node_modules/
    depends_on:
      - hotels
      - database
  hotels:
    build: ./services/hotels
    container_name: almundo-hotels-service
    command: npm run start:docker
    ports:
      - '5000:5000'
    volumes:
      - './services/hotels/:/usr/src/hotels'
      - /usr/src/hotels/node_modules/
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=almundo
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./scripts/mongo/:/docker-entrypoint-initdb.d/
